theme: minima
title: Blagorf
author: Jayden Gong
excerpt_separator: <!--excerpt-->
header_pages:
  - index.md
  - ascii.md
  - spirograph.md
  - diary.md
  - about.md
collections:
  diaries:
    output: true
